### ISSUE TITLE
[RSK] How to use RSK?

### ISSUE THREAD

**Issue by IntinteDAO** [protofire/eth-cli#118]
Hello, I added, according to the documentation, support for RSK (network:add), which confirms the eth networks. But I don't know how to invoke commands in RSK network, the --rsk parameter doesn't work

eth block:get --rsk 100,000
 Error: Unexpected argument: 100000

And other commands don't work well. So what should a correct command for RSK look like?

**Comment by fvictorio** [comment]
Hi @IntinteDAO. Custom networks are used with the `--network` flag (or just `-n`):

```
eth network:add rsk ...
eth block:get -n rsk
```

should work.

**Comment by IntinteDAO** [comment]
Works, thanks
