### ISSUE TITLE
Custom gas price

### ISSUE THREAD

**Issue by IntinteDAO** [protofire/eth-cli#130]
I didn't find this option in the commands or help, so I assume it's not.

I could use a command like this for transaction:send.

**Comment by IntinteDAO** [comment]
https://github.com/protofire/eth-cli/issues/96
I think value was added, but without gas price ...?

**Comment by fvictorio** [comment]
Hey @IntinteDAO, `eth tx:send` should support it. Let me know if it doesn't work for you.

`eth tx:nop` and `eth contract:send` should support it, but they don't, I will open an issue for that.

**Comment by IntinteDAO** [comment]
Yep, works (I think), I just didn't find this option in help menu, but it was there ;)
