### ISSUE TITLE
Gwei

### ISSUE THREAD

**Issue by noirorionx** [protofire/eth-cli#149]
Is there any possible way to adjust the Gwei and amount of gas we use for a tx? 

Thank you for your amazing work!

**Comment by fvictorio** [comment]
These are currently supported:

```
$ eth tx:send --help
...
  --gas=gas                                  The gas limit of the transaction. Will be estimated if not
                                             specified.

  --gasPrice=gasPrice                        The gas price of the transaction, in wei. Defaults to 1 gwei.
...
```

Does that work for you?

**Comment by noirorionx** [comment]
Thank you very much! that was exactly what I was looking for!! Love your tool, thank you so much!

**Comment by noirorionx** [comment]
tried to use it with "contract:send" and returns following error: "Error: Unexpected argument: --gasPrice=70000000000" 
Also tried with --gas command and same error return.

Maybe this parameters can't be use on "contract:send"?

Thank you!
