### ISSUE TITLE
Look for alternatives to yargs

### ISSUE THREAD

**Issue by fernandomg** [protofire/eth-cli#22]
e.g. global options are available to all the commands when there are cases where that they are unnecessary.

For instance, when running `eth network --help` there are several global options that shouldn't be displayed.
![image](https://user-images.githubusercontent.com/3315606/45241720-dc593200-b2c3-11e8-922b-599fbb5ed741.png)

**Comment by fvictorio** [comment]
[oclif](https://github.com/oclif/oclif) looks nice

**Comment by mariano-aguero** [comment]
before switching to another library, we should add tests, I will create an issue #36

**Comment by mariano-aguero** [comment]
See PR #45 for more.
