### ISSUE TITLE
Improve multiple contracts naming

### ISSUE THREAD

**Issue by fernandomg** [protofire/eth-cli#30]
From this conversation https://github.com/protofire/eth-cli/pull/29#discussion_r219836577

Contracts naming in the REPL context can be improved.

A suggestion I have is to use the `abi` file name and part of its name, instead of adding a suffix. For instance:

`eth lc --mainnet path/to/ERC20.abi 0x another/path/to/ERC20.abi 0x path/to/ERC725.abi 0x`

Will result in: `ERC20, ERC20_to_path_another, ERC725`

Now that I wrote it down, it may be a bit awkward if the path is too long, but we can think of a name length limit and from there start to add suffixes.

**Comment by fvictorio** [comment]
Now that we have the `erc20` known ABI, this isn't a great experience (if you load two tokens, one of them is called `erc20_1`), but I think it's good enough. You can always do `foo = erc20; bar = erc20_1` manually.

There is room for improvement here, of course. Maybe the contract loading "syntax" can be extends with an optional name. Or maybe, if you are loading erc20 contracts, you can call the "symbol" method and use that as the name (I hate this idea, btw). But I don't think it's necessary right now. If this annoys someone, please open a new issue.
