### ISSUE TITLE
Allow inline call to a specific method from a specific contract

### ISSUE THREAD

**Issue by pablofullana** [protofire/eth-cli#39]
It would be really handy to make an inline call to a specific method from a specific contract.

A possible command would be something in the fashion of: 

`eth <contract> <method> <args>`

**Comment by fernandomg** [comment]
To be able to call a contract method we'll require the contract's ABI as well. So a new parameter will be required (the ABI file) to properly encode the method call. 

With that in mind, we can create two different commands that will solve different problems, and combine them to solve this particular issue. Thus, the commands will be:
 - one for `encode` the ABI, e.g.:
   - `eth encode Contract.abi 'myMethod(1,2)'`
 - the other one for `send`ing the transaction, e.g.:
   - `eth send --data <encodedABI> <contractAddress> <pk>`

With that we can combine both commands:
```
eth send --data `eth encode Contract.abi 'myMethod(1,2)'` 0x123... 0x444...
```
