### ISSUE TITLE
Display wallet private key as part of random-address command output

### ISSUE THREAD

**Issue by pablofullana** [protofire/eth-cli#42]
### Goal
Original request by @ArseniiPetrovich was to have a command in the fashion of `eth-cli ra`, that generates wallet's address but also outputs its private part (supporting JSON format as well)

### Internal discussion notes
`eth vanity ''` already does that, but it's kind of a side effect actually. Maybe the three things could be integrated under one command:
1. `eth random-address` To generate a random address
1. `eth random-address --full` To generate a JSON with the address and corresponding private key
1. `eth random-address --prefix aa` Same as `eth vanity aa`
1.  Another option is to, by default, output the JSON, and have a flag `--only-address`

A simpler version could be:
1. `eth random-address` To generate a JSON with the address and the private key.
1. `eth random-address --prefix aa` Same as `eth vanity aa`

Let's discuss these (and any other) alternatives

**Comment by fernandomg** [comment]
So far from what was discussed, the best option will be to go with the simpler version. Thus, `eth ra` will always return a JSON object with `address` and `privateKey`.
