### ISSUE TITLE
Problem with contract:deploy 

### ISSUE THREAD

**Issue by nicosampler** [protofire/eth-cli#67]
I've found a problem trying to deploy a contract.

For example running this command `eth contract:deploy --ropsten 0x0fb78ee19db8da275893a7b6aa176edc09699e56bb0ba63ff6affa70660da4e9 ./MyPhrase.bin` It took a lot of time and at the end it finished the execution without any visible result.

**Comment by fvictorio** [comment]
@nicosampler was this fixed by #68? Can we close it?

**Comment by nicosampler** [comment]
yes!
