### ISSUE TITLE
What do you think about adding semanticrelease?

### ISSUE THREAD

**Issue by nicosampler** [protofire/eth-cli#69]
I think that adding this [lib](https://github.com/semantic-release/semantic-release) could be very useful to respect semver and also to automate the publication to npm.

**Comment by fvictorio** [comment]
I like this idea a lot. Some comments:

- If we add this, then we should also add https://github.com/conventional-changelog/commitlint
- This also means that we should move work to a `development` branch, and merge `development` into `master` when we want to publish a new version
- We are using 2FA for publishing in npm, so we'll need to add a deploy token to Travis

I will change the base branch to develop, that way all new PRs will be created against that. @nicosampler can you create a PR that adds `commitlint`? When that it's done, I'll take care of the rest of the steps.

**Comment by nicosampler** [comment]
Yes, I can. 
Another comments
- we need to create a tag in github for each version already published in npm. I think that it should be  like this `v1.0.0-alpha-4`.
- Configure semantic-release with the plugin for git, this will update the package.json automatically.
```
["@semantic-release/git", {
      "assets": ["package.json"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
}]
```
- Configure semantic-release with the plugin for release-notes-generator, this will update the changelog.md
```
["@semantic-release/release-notes-generator", {
      "preset": "angular",
      "parserOpts": {
        "noteKeywords": ["BREAKING CHANGE", "feat", "fix"]
      },
      "writerOpts": {
        "commitsSort": ["subject", "scope"]
      }
}]
```
