### ISSUE TITLE
Refactor: we need to find a better way to normalize the transactionconfirmationblocks option for web3.

### ISSUE THREAD

**Issue by nicosampler** [protofire/eth-cli#78]
Now, we are duplicating the code.

**Comment by fvictorio** [comment]
See also #89.

**Comment by fvictorio** [comment]
I think this is handled in #99. @nicosampler, if you agree, please close this issue.

**Comment by nicosampler** [comment]
@fvictorio I left a comment here: https://github.com/protofire/eth-cli/pull/99/files#r319035707. If you think that is not needed I will close it.
